package it.italiangrid.portal.dirac.db.domain;

// Generated 26-mar-2013 11.36.50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * JobParameters generated by hbm2java
 */
@Entity
@Table(name = "JobParameters", catalog = "JobDB")
public class JobParameters implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6431810737822774265L;
	private JobParametersId id;
	private byte[] value;

	public JobParameters() {
	}

	public JobParameters(JobParametersId id, byte[] value) {
		this.id = id;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobId", column = @Column(name = "JobID", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "Name", nullable = false, length = 100)) })
	public JobParametersId getId() {
		return this.id;
	}

	public void setId(JobParametersId id) {
		this.id = id;
	}

	@Column(name = "Value", nullable = false)
	public byte[] getValue() {
		return this.value;
	}

	public void setValue(byte[] value) {
		this.value = value;
	}

}
