package it.italiangrid.portal.dirac.db.domain;

// Generated 26-mar-2013 11.36.50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name = "Jobs", catalog = "JobDB")
public class Jobs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5054646062967864252L;
	private long jobId;
	private String jobType;
	private String diracsetup;
	private String jobGroup;
	private String jobSplitType;
	private long masterJobId;
	private String site;
	private String jobName;
	private String owner;
	private String ownerDn;
	private String ownerGroup;
	private Date submissionTime;
	private Date rescheduleTime;
	private Date lastUpdateTime;
	private Date startExecTime;
	private Date heartBeatTime;
	private Date endExecTime;
	private String status;
	private String minorStatus;
	private String applicationStatus;
	private int applicationNumStatus;
	private float cputime;
	private int userPriority;
	private int systemPriority;
	private int rescheduleCounter;
	private String verifiedFlag;
	private String deletedFlag;
	private String killedFlag;
	private String failedFlag;
	private String isandboxReadyFlag;
	private String osandboxReadyFlag;
	private String retrievedFlag;
	private String accountedFlag;

	public Jobs() {
	}

	public Jobs(String jobType, String diracsetup, String jobGroup,
			String jobSplitType, long masterJobId, String site, String jobName,
			String owner, String ownerDn, String ownerGroup, String status,
			String minorStatus, String applicationStatus,
			int applicationNumStatus, float cputime, int userPriority,
			int systemPriority, int rescheduleCounter, String verifiedFlag,
			String deletedFlag, String killedFlag, String failedFlag,
			String isandboxReadyFlag, String osandboxReadyFlag,
			String retrievedFlag, String accountedFlag) {
		this.jobType = jobType;
		this.diracsetup = diracsetup;
		this.jobGroup = jobGroup;
		this.jobSplitType = jobSplitType;
		this.masterJobId = masterJobId;
		this.site = site;
		this.jobName = jobName;
		this.owner = owner;
		this.ownerDn = ownerDn;
		this.ownerGroup = ownerGroup;
		this.status = status;
		this.minorStatus = minorStatus;
		this.applicationStatus = applicationStatus;
		this.applicationNumStatus = applicationNumStatus;
		this.cputime = cputime;
		this.userPriority = userPriority;
		this.systemPriority = systemPriority;
		this.rescheduleCounter = rescheduleCounter;
		this.verifiedFlag = verifiedFlag;
		this.deletedFlag = deletedFlag;
		this.killedFlag = killedFlag;
		this.failedFlag = failedFlag;
		this.isandboxReadyFlag = isandboxReadyFlag;
		this.osandboxReadyFlag = osandboxReadyFlag;
		this.retrievedFlag = retrievedFlag;
		this.accountedFlag = accountedFlag;
	}

	public Jobs(String jobType, String diracsetup, String jobGroup,
			String jobSplitType, long masterJobId, String site, String jobName,
			String owner, String ownerDn, String ownerGroup,
			Date submissionTime, Date rescheduleTime, Date lastUpdateTime,
			Date startExecTime, Date heartBeatTime, Date endExecTime,
			String status, String minorStatus, String applicationStatus,
			int applicationNumStatus, float cputime, int userPriority,
			int systemPriority, int rescheduleCounter, String verifiedFlag,
			String deletedFlag, String killedFlag, String failedFlag,
			String isandboxReadyFlag, String osandboxReadyFlag,
			String retrievedFlag, String accountedFlag) {
		this.jobType = jobType;
		this.diracsetup = diracsetup;
		this.jobGroup = jobGroup;
		this.jobSplitType = jobSplitType;
		this.masterJobId = masterJobId;
		this.site = site;
		this.jobName = jobName;
		this.owner = owner;
		this.ownerDn = ownerDn;
		this.ownerGroup = ownerGroup;
		this.submissionTime = submissionTime;
		this.rescheduleTime = rescheduleTime;
		this.lastUpdateTime = lastUpdateTime;
		this.startExecTime = startExecTime;
		this.heartBeatTime = heartBeatTime;
		this.endExecTime = endExecTime;
		this.status = status;
		this.minorStatus = minorStatus;
		this.applicationStatus = applicationStatus;
		this.applicationNumStatus = applicationNumStatus;
		this.cputime = cputime;
		this.userPriority = userPriority;
		this.systemPriority = systemPriority;
		this.rescheduleCounter = rescheduleCounter;
		this.verifiedFlag = verifiedFlag;
		this.deletedFlag = deletedFlag;
		this.killedFlag = killedFlag;
		this.failedFlag = failedFlag;
		this.isandboxReadyFlag = isandboxReadyFlag;
		this.osandboxReadyFlag = osandboxReadyFlag;
		this.retrievedFlag = retrievedFlag;
		this.accountedFlag = accountedFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JobID", unique = true, nullable = false)
	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	@Column(name = "JobType", nullable = false, length = 32)
	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	@Column(name = "DIRACSetup", nullable = false, length = 32)
	public String getDiracsetup() {
		return this.diracsetup;
	}

	public void setDiracsetup(String diracsetup) {
		this.diracsetup = diracsetup;
	}

	@Column(name = "JobGroup", nullable = false, length = 32)
	public String getJobGroup() {
		return this.jobGroup;
	}

	public void setJobGroup(String jobGroup) {
		this.jobGroup = jobGroup;
	}

	@Column(name = "JobSplitType", nullable = false, length = 7)
	public String getJobSplitType() {
		return this.jobSplitType;
	}

	public void setJobSplitType(String jobSplitType) {
		this.jobSplitType = jobSplitType;
	}

	@Column(name = "MasterJobID", nullable = false)
	public long getMasterJobId() {
		return this.masterJobId;
	}

	public void setMasterJobId(long masterJobId) {
		this.masterJobId = masterJobId;
	}

	@Column(name = "Site", nullable = false, length = 100)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "JobName", nullable = false, length = 128)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "Owner", nullable = false, length = 32)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "OwnerDN", nullable = false)
	public String getOwnerDn() {
		return this.ownerDn;
	}

	public void setOwnerDn(String ownerDn) {
		this.ownerDn = ownerDn;
	}

	@Column(name = "OwnerGroup", nullable = false, length = 128)
	public String getOwnerGroup() {
		return this.ownerGroup;
	}

	public void setOwnerGroup(String ownerGroup) {
		this.ownerGroup = ownerGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SubmissionTime", length = 19)
	public Date getSubmissionTime() {
		return this.submissionTime;
	}

	public void setSubmissionTime(Date submissionTime) {
		this.submissionTime = submissionTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RescheduleTime", length = 19)
	public Date getRescheduleTime() {
		return this.rescheduleTime;
	}

	public void setRescheduleTime(Date rescheduleTime) {
		this.rescheduleTime = rescheduleTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdateTime", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartExecTime", length = 19)
	public Date getStartExecTime() {
		return this.startExecTime;
	}

	public void setStartExecTime(Date startExecTime) {
		this.startExecTime = startExecTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HeartBeatTime", length = 19)
	public Date getHeartBeatTime() {
		return this.heartBeatTime;
	}

	public void setHeartBeatTime(Date heartBeatTime) {
		this.heartBeatTime = heartBeatTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndExecTime", length = 19)
	public Date getEndExecTime() {
		return this.endExecTime;
	}

	public void setEndExecTime(Date endExecTime) {
		this.endExecTime = endExecTime;
	}

	@Column(name = "Status", nullable = false, length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "MinorStatus", nullable = false, length = 128)
	public String getMinorStatus() {
		return this.minorStatus;
	}

	public void setMinorStatus(String minorStatus) {
		this.minorStatus = minorStatus;
	}

	@Column(name = "ApplicationStatus", nullable = false, length = 256)
	public String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	@Column(name = "ApplicationNumStatus", nullable = false)
	public int getApplicationNumStatus() {
		return this.applicationNumStatus;
	}

	public void setApplicationNumStatus(int applicationNumStatus) {
		this.applicationNumStatus = applicationNumStatus;
	}

	@Column(name = "CPUTime", nullable = false, precision = 12, scale = 0)
	public float getCputime() {
		return this.cputime;
	}

	public void setCputime(float cputime) {
		this.cputime = cputime;
	}

	@Column(name = "UserPriority", nullable = false)
	public int getUserPriority() {
		return this.userPriority;
	}

	public void setUserPriority(int userPriority) {
		this.userPriority = userPriority;
	}

	@Column(name = "SystemPriority", nullable = false)
	public int getSystemPriority() {
		return this.systemPriority;
	}

	public void setSystemPriority(int systemPriority) {
		this.systemPriority = systemPriority;
	}

	@Column(name = "RescheduleCounter", nullable = false)
	public int getRescheduleCounter() {
		return this.rescheduleCounter;
	}

	public void setRescheduleCounter(int rescheduleCounter) {
		this.rescheduleCounter = rescheduleCounter;
	}

	@Column(name = "VerifiedFlag", nullable = false, length = 5)
	public String getVerifiedFlag() {
		return this.verifiedFlag;
	}

	public void setVerifiedFlag(String verifiedFlag) {
		this.verifiedFlag = verifiedFlag;
	}

	@Column(name = "DeletedFlag", nullable = false, length = 5)
	public String getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(String deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	@Column(name = "KilledFlag", nullable = false, length = 5)
	public String getKilledFlag() {
		return this.killedFlag;
	}

	public void setKilledFlag(String killedFlag) {
		this.killedFlag = killedFlag;
	}

	@Column(name = "FailedFlag", nullable = false, length = 5)
	public String getFailedFlag() {
		return this.failedFlag;
	}

	public void setFailedFlag(String failedFlag) {
		this.failedFlag = failedFlag;
	}

	@Column(name = "ISandboxReadyFlag", nullable = false, length = 5)
	public String getIsandboxReadyFlag() {
		return this.isandboxReadyFlag;
	}

	public void setIsandboxReadyFlag(String isandboxReadyFlag) {
		this.isandboxReadyFlag = isandboxReadyFlag;
	}

	@Column(name = "OSandboxReadyFlag", nullable = false, length = 5)
	public String getOsandboxReadyFlag() {
		return this.osandboxReadyFlag;
	}

	public void setOsandboxReadyFlag(String osandboxReadyFlag) {
		this.osandboxReadyFlag = osandboxReadyFlag;
	}

	@Column(name = "RetrievedFlag", nullable = false, length = 5)
	public String getRetrievedFlag() {
		return this.retrievedFlag;
	}

	public void setRetrievedFlag(String retrievedFlag) {
		this.retrievedFlag = retrievedFlag;
	}

	@Column(name = "AccountedFlag", nullable = false, length = 6)
	public String getAccountedFlag() {
		return this.accountedFlag;
	}

	public void setAccountedFlag(String accountedFlag) {
		this.accountedFlag = accountedFlag;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Jobs [jobId=" + jobId + ", jobType=" + jobType
				+ ", diracsetup=" + diracsetup + ", jobGroup=" + jobGroup
				+ ", jobSplitType=" + jobSplitType + ", masterJobId="
				+ masterJobId + ", site=" + site + ", jobName=" + jobName
				+ ", owner=" + owner + ", ownerDn=" + ownerDn + ", ownerGroup="
				+ ownerGroup + ", submissionTime=" + submissionTime
				+ ", rescheduleTime=" + rescheduleTime + ", lastUpdateTime="
				+ lastUpdateTime + ", startExecTime=" + startExecTime
				+ ", heartBeatTime=" + heartBeatTime + ", endExecTime="
				+ endExecTime + ", status=" + status + ", minorStatus="
				+ minorStatus + ", applicationStatus=" + applicationStatus
				+ ", applicationNumStatus=" + applicationNumStatus
				+ ", cputime=" + cputime + ", userPriority=" + userPriority
				+ ", systemPriority=" + systemPriority + ", rescheduleCounter="
				+ rescheduleCounter + ", verifiedFlag=" + verifiedFlag
				+ ", deletedFlag=" + deletedFlag + ", killedFlag=" + killedFlag
				+ ", failedFlag=" + failedFlag + ", isandboxReadyFlag="
				+ isandboxReadyFlag + ", osandboxReadyFlag="
				+ osandboxReadyFlag + ", retrievedFlag=" + retrievedFlag
				+ ", accountedFlag=" + accountedFlag + "]";
	}

}
